### ISSUE TITLE
Getting stack trace exception with Smart Moving

### ISSUE THREAD

**Issue by EzerArch** [RiskyKen/Armourers-Workshop#109]
Every time I load AW with SM moving I get this error, no crashes:

```
[22:03:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: java.lang.Exception: Stack trace
[22:03:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at java.lang.Thread.dumpStack(Unknown Source)
[22:03:56] [Client thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:-1]: 	at riskyken.armourersWorkshop.client.render.EquipmentModelRenderer.onRender(EquipmentModelRenderer.java:204)
```

Full log: https://gist.github.com/EzerArch/95f476972c87d2dff2f19b662ebabf2e#file-armourers-workshop-sm-L933

**Comment by RiskyKen** [comment]
Oh forgot about that was just dumping that when debugging stuff in smart moving. Will remove!
