### ISSUE TITLE
Game Crash - java.lang.NullPointerException: Rendering item

### ISSUE THREAD

**Issue by alex5219** [RiskyKen/Armourers-Workshop#159]
The game experiences a crash whenever I enter the second creative tab. Here is the full crash report:
`---- Minecraft Crash Report ----
// Oops.

Time: 3/19/17 6:51 PM
Description: Rendering item

java.lang.NullPointerException: Rendering item
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:402)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:929)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:760)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1400)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at net.minecraft.item.ItemStack.func_77960_j(ItemStack.java:217)
	at net.minecraft.client.renderer.entity.RenderItem.renderItemIntoGUI(RenderItem.java:402)
	at net.minecraft.client.renderer.entity.RenderItem.func_82406_b(RenderItem.java:565)

-- Item being rendered --
Details:
	Item Type: null
	Item Aux: ~~ERROR~~ NullPointerException: null
	Item NBT: null
	Item Foil: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147051_a(GuiContainerCreative.java:929)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146976_a(GuiContainerCreative.java:760)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73863_a(GuiContainer.java:78)
	at net.minecraft.client.renderer.InventoryEffectRenderer.func_73863_a(InventoryEffectRenderer.java:38)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_73863_a(GuiContainerCreative.java:638)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1400)

-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative
	Mouse location: Scaled: (430, 74). Absolute: (861, 557)
	Screen size: Scaled: (683, 353). Absolute: (1366, 705). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 2 total; [EntityClientPlayerMP['Awex__'/634, l='MpServer', x=380.94, y=36.62, z=130.52], MCH_ViewEntityDummy['McHeliDummyEntity'/67, l='MpServer', x=0.00, y=-4.00, z=0.00]]
	Chunk stats: MultiplayerChunkCache: 1089, 1089
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (482,116,135), Chunk: (at 2,7,7 in 30,8; contains blocks 480,0,128 to 495,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 16459846 game time, 72000 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 8 total; [EntityCustomNpc['BBovard'/210, l='MpServer', x=361.63, y=35.00, z=130.31], EntityCustomNpc['Zen_Soul'/211, l='MpServer', x=361.50, y=35.00, z=136.50], MCH_ViewEntityDummy['McHeliDummyEntity'/67, l='MpServer', x=0.00, y=-4.00, z=0.00], EntityCustomNpc['Awex__'/212, l='MpServer', x=360.50, y=35.00, z=134.50], EntityCustomNpc['the345crew'/213, l='MpServer', x=360.50, y=35.00, z=132.50], EntityCustomNpc['__Governor__'/216, l='MpServer', x=368.50, y=35.00, z=123.50], EntityClientPlayerMP['Awex__'/634, l='MpServer', x=380.94, y=36.62, z=130.52], EntityCustomNpc['Divided_War'/221, l='MpServer', x=387.50, y=35.00, z=144.50]]
	Retry entities: 0 total; []
	Server brand: thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_73, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7008141096 bytes (6683 MB) / 7516192768 bytes (7168 MB) up to 7516192768 bytes (7168 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms7168m -Xmx7168m -XX:+UseG1GC -XX:MaxGCPauseMillis=4
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_D6 32 mods loaded, 32 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{7.10.99.99} [Forge Mod Loader] (modpack.jar) 
	UCHIJA	Forge{10.13.4.1614} [Minecraft Forge] (modpack.jar) 
	UCHIJA	CodeChickenCore{1.0.7.47} [CodeChicken Core] (minecraft.jar) 
	UCHIJA	NotEnoughItems{1.0.5.120} [Not Enough Items] (NEI.jar) 
	UCHIJA	PlayerAPI{1.4} [Player API] (minecraft.jar) 
	UCHIJA	RenderPlayerAPI{1.4} [Render Player API] (minecraft.jar) 
	UCHIJA	FastCraft{1.23} [FastCraft] (Fast Craft.jar) 
	UCHIJA	armourersWorkshop{1.7.10-0.42.5} [Armourer's Workshop] (Armour's Workshop.jar) 
	UCHIJA	plushieWrapper{0.0.0} [Plushie Wrapper] (Armour's Workshop.jar) 
	UCHIJA	betterloadingscreen{1.3.8} [Better Loading Screen] (Better Loading Screen.jar) 
	UCHIJA	MineTweaker3{3.0.12} [MineTweaker 3] (CraftTweaker.jar) 
	UCHIJA	customnpcs{1.7.10d} [CustomNpcs] (Custom NPCS.jar) 
	UCHIJA	props{1.10} [Decocraft] (Deco Craft.zip) 
	UCHIJA	fiskheroes{1.0.13} [Fisk's Superheroes] (Fisks Superheroes.jar) 
	UCHIJA	flansmod{4.10.0} [Flan's Mod] (Flans.jar) 
	UCHIJA	cfm{3.4.8} [�9MrCrayfish's Furniture Mod] (Furniture Mod.jar) 
	UCHIJA	grapplemod{1.7.10-v9} [Grappling hook mod] (Grappling Hooks.jar) 
	UCHIJA	itlt{0.0.8} [It's the little things] (itIt.jar) 
	UCHIJA	journeymap{5.1.4p2} [JourneyMap] (Journey Map.jar) 
	UCHIJA	CustomMainMenu{1.9.2} [Custom Main Menu] (Main Menu.jar) 
	UCHIJA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle.jar) 
	UCHIJA	mcheli{1.0.2} [MC Helicopter] (MCHeli) 
	UCHIJA	packguard{2.3.0} [PackGuard] (Mods Checker.jar) 
	UCHIJA	ResourceLoader{1.2} [Resource Loader] (Resource Loader.jar) 
	UCHIJA	secretroomsmod{4.7.1} [The SecretRoomsMod] (Secret Rooms Mod.jar) 
	UCHIJA	legends{1.6} [Legends Mod] (Superheroes Core.jar) 
	UCHIJA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct.jar) 
	UCHIJA	ironman{4.3.12} [Iron Man Armor Extension] (Typhos Superheroes.jar) 
	UCHIJA	sus{4.3.12} [Superheroes Unlimited Mod] (Typhos Superheroes.jar) 
	UCHIJA	susaddon{4.3.12} [Superheroes Unlimited Mod (Part 2)] (Typhos Superheroes.jar) 
	UCHIJA	gvc{0.6.1} [�aGliby's�f Voice Chat Mod] (Voice Chat.jar) 
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	PackGuard: MISSING: BiomesOPlenty v2.1.0, ADDED: armourersWorkshop v1.7.10-0.42.5, 
ADDED: plushieWrapper v0.0.0
	Launched Version: 1.7.10-Forge10.13.4.1614-1.7.10
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.4358, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
	OptiFine Version: OptiFine_1.7.10_HD_U_D6
	Render Distance Chunks: 28
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	OpenGlVersion: 4.0.0 - Build 10.18.10.4358
	OpenGlRenderer: Intel(R) HD Graphics 4000
	OpenGlVendor: Intel
	CpuCount: 2`

**Comment by alex5219** [comment]
Just read the crash log nvm.

**Comment by alex5219** [comment]
Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine

I thought this was the reason for the crash, however when I removed optfiine it still caused the same crash.

**Comment by RiskyKen** [comment]
I don't see anything here to do with my mod. Could be a conflict with RenderPlayerAPI could you try removing it to see if that works.

**Comment by Awex0101** [comment]
This crash is due to a client side having the mod and the server does not. Whenever you go to the creative tab it is located in it just goes RIP.
