### ISSUE TITLE
[BUG] Connection Lost: Invalid Player data with Inventive Inventory

### ISSUE THREAD

**Issue by Poopooracoocoo** [RiskyKen/Armourers-Workshop#494]
**Describe the bug**

**To Reproduce**
1. Launch game
2. Click singleplayer
3. Create world

**Expected behavior**
Join world

**Screenshots**

**Crash report**
[crash-2024-12-05_04.04.32-client.txt](https://github.com/user-attachments/files/18011792/crash-2024-12-05_04.04.32-client.txt)

**Log**

[latest.log](https://github.com/user-attachments/files/18011788/latest.log)

<details><summary>Details</summary>

```
[Server thread/ERROR]: Couldn't place player in world
net.minecraft.class_148: Adding item to inventory
	at net.minecraft.class_1661.method_7367(class_1661.java:311) ~[client-intermediary.jar:?]
	at net.minecraft.class_1661.method_7394(class_1661.java:263) ~[client-intermediary.jar:?]
	at moe.plushie.armourers_workshop.init.ModHolidays.welcome(ModHolidays.java:79) ~[armourersworkshop-fabric-1.20.1-3.0.0-beta.25.jar:?]
	at moe.plushie.armourers_workshop.init.proxy.CommonProxy.lambda$register$6(CommonProxy.java:98) ~[armourersworkshop-fabric-1.20.1-3.0.0-beta.25.jar:?]
	at moe.plushie.armourers_workshop.compatibility.fabric.event.common.AbstractFabricPlayerEvent.lambda$loggingInFactory$1(AbstractFabricPlayerEvent.java:18) ~[armourersworkshop-fabric-1.20.1-3.0.0-beta.25.jar:?]
	at net.fabricmc.fabric.api.networking.v1.ServerPlayConnectionEvents.lambda$static$2(ServerPlayConnectionEvents.java:48) ~[fabric-networking-api-v1-1.3.11+1802ada577-a65c3ef3908d32fd.jar:?]
	at net.fabricmc.fabric.impl.networking.server.ServerPlayNetworkAddon.onClientReady(ServerPlayNetworkAddon.java:66) ~[fabric-networking-api-v1-1.3.11+1802ada577-a65c3ef3908d32fd.jar:?]
	at net.minecraft.class_3324.handler$zih000$fabric-networking-api-v1$handlePlayerConnection(class_3324.java:2518) ~[client-intermediary.jar:?]
	at net.minecraft.class_3324.method_14570(class_3324.java:215) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_33800(class_3248.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_14384(class_3248.java:118) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.redirect$zii000$fabric-networking-api-v1$handlePlayerJoin(class_3248.java:563) ~[client-intermediary.jar:?]
	at net.minecraft.class_3248.method_18784(class_3248.java:68) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[client-intermediary.jar:?]
	at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:105) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot read field "field_7512" because the return value of "net.origins.inventive_inventory.InventiveInventory.getPlayer()" is null
	at net.origins.inventive_inventory.InventiveInventory.getScreenHandler(InventiveInventory.java:61) ~[inventive_inventory-1.1.1.jar:?]
	at net.origins.inventive_inventory.features.locked_slots.LockedSlots.adjust(LockedSlots.java:18) ~[inventive_inventory-1.1.1.jar:?]
	at net.origins.inventive_inventory.features.locked_slots.LockedSlotsHandler.getLockedSlots(LockedSlotsHandler.java:70) ~[inventive_inventory-1.1.1.jar:?]
	at net.minecraft.class_1661.modifyExpressionValue$zod000$inventive_inventory$stackIsEmptyAndNotLockedSlot(class_1661.java:689) ~[client-intermediary.jar:?]
	at net.minecraft.class_1661.method_7376(class_1661.java:77) ~[client-intermediary.jar:?]
	at net.minecraft.class_1661.method_7366(class_1661.java:197) ~[client-intermediary.jar:?]
	at net.minecraft.class_1661.method_7367(class_1661.java:277) ~[client-intermediary.jar:?]
	... 20 more
``` 

</details> 

**Additional context**

**Comment by SAGESSE-CN** [comment]
pls report to inventive inventory
