### ISSUE TITLE
Crash with LiteLoader

### ISSUE THREAD

**Issue by Swablydaloo** [RiskyKen/Armourers-Workshop#76]
I ran my minecraft 1.7.10 Forge and 1.7.10 Litemod and I found out that it doesn't work. (Just with Voxelmap for Litemod and AW for Forge. Nothing else.) I'll paste the detailed walkthrough.
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at java.nio.Buffer.checkIndex(Buffer.java:540)
    at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:253)
    at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:350)
    at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294)
    at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216)
    at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146)
    at net.minecraft.client.network.NetHandlerPlayClient.func_147282_a(NetHandlerPlayClient.java:240)
    at com.mumfrey.liteloader.client.PacketEventsClient.handlePacket(PacketEventsClient.java:106)
    at com.mumfrey.liteloader.core.PacketEvents.handlePacketEvent(PacketEvents.java:179)
    at com.mumfrey.liteloader.core.PacketEvents.handlePacket(PacketEvents.java:134)
    at com.mumfrey.liteloader.core.PacketEvents.handlePacket(PacketEvents.java:129)
    at com.mumfrey.liteloader.core.event.EventProxy$2.$event00024(Unknown Source)
    at net.minecraft.network.play.server.S01PacketJoinGame.func_148833_a(SourceFile)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)

-- Affected level --
Details:
    Level name: MpServer
    All players: 0 total; []
    Chunk stats: MultiplayerChunkCache: 0, 0
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (8,64,8), Chunk: (at 8,4,8 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
    Level time: 0 game time, 0 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 0 total; []
    Retry entities: 0 total; []
    Server brand: ~~ERROR~~ NullPointerException: null
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 68260728 bytes (65 MB) / 328884224 bytes (313 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.3.1428 5 mods loaded, 5 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.3.1428-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.3.1428} [Minecraft Forge](forge-1.7.10-10.13.3.1428-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    armourersWorkshop{1.7.10-0.37.0.94} [Armourer's Workshop](Armourers-Workshop-1.7.10-0.37.0.94.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    plushieWrapper{0.0.0} [Plushie Wrapper](Armourers-Workshop-1.7.10-0.37.0.94.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.15.4256' Renderer: 'Intel(R) HD Graphics 4600'
    Launched Version: 1.7.10
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics 4600 GL version 4.3.0 - Build 10.18.15.4256, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (UK)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by RiskyKen** [comment]
Looks like the crash is coming from lite loader. Will have a look at it later.

**Comment by Badcholo** [comment]
leave it that way, i hate players using lite loader to cheat

**Comment by RiskyKen** [comment]
@Badcholo LiteLoader is not for cheating, people can use forge to cheat as well.

**Comment by Badcholo** [comment]
I just want it to die. it has like 10 mods and all useless.

**Comment by RiskyKen** [comment]
Unable to reproduce. Make sure you have the latest LL and Forge.
