### ISSUE TITLE
Attempted to load class ClientModelCache for invalid side SERVER

### ISSUE THREAD

**Issue by joserobjr** [RiskyKen/Armourers-Workshop#81]
Somebody used something from Armourer's Workshop on the server and caused it to crash. The Crash report:

```
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: riskyken/armourersWorkshop/client/model/ClientModelCache
        at riskyken.armourersWorkshop.common.items.ItemEquipmentSkin.func_77653_i(ItemEquipmentSkin.java:50)
        at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:491)
        at myessentials.entities.tool.ToolManager.onPlayerLogout(ToolManager.java:97)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_65_ToolManager_onPlayerLogout_PlayerLoggedOutEvent.invoke(.dynamic)
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
        at cpw.mods.fml.common.FMLCommonHandler.firePlayerLoggedOut(FMLCommonHandler.java:574)
        at net.minecraft.server.management.ServerConfigurationManager.disconnect(ServerConfigurationManager.java:436)
        at net.minecraft.network.NetHandlerPlayServer.func_147231_a(NetHandlerPlayServer.java:945)
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:166)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:980)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:430)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: riskyken.armourersWorkshop.client.model.ClientModelCache
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 15 more
Caused by: java.lang.RuntimeException: Attempted to load class riskyken/armourersWorkshop/client/model/ClientModelCache for invalid side SERVER
        at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:51)
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
        ... 17 more
```

Full crash report:
[crash-2015-11-17_20.36.37-server.txt](https://github.com/RiskyKen/Armourers-Workshop/files/37343/crash-2015-11-17_20.36.37-server.txt)

**Comment by RiskyKen** [comment]
Related to https://github.com/RiskyKen/Armourers-Workshop/issues/72 will be fixed in the next update.
